package pl.snowboard4humans.enums;

import lombok.AllArgsConstructor;
import lombok.Getter;

@Getter
@AllArgsConstructor
public enum CategoryPLEnum {
  SNOWBOARDS("DESKI SNOWBOARDOWE"),
  SNOWBOARDSHOES("BUTY SNOWBOARDOWE"),
  SNOWBOARDBINDINGS("WIĄZANIA SNOWBOARDOWE"),
  SNOWBOARDGLOVES("RĘKAWICE SNOWBOARDOWE"),
  SNOWBOARDGOGGLES("GOGLE SNOWBOARDOWE"),
  SNOWBOARDHELMETS("KASKI SNOWBOARDOWE"),
  THERMOACTIVECLOTHING("ODZIEŻ TERMOAKTYWANA"),
  ZERO("BRAK");

  private final String category;
}
